name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Build
      run: docker build -f ./Containerfile -t ssh-prometheus-exporter .

    - name: Sanity check
      run: docker run ssh-prometheus-exporter --version
